In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [11]:
data = pd.read_csv('../data/motor_vehicle_collisions_crashes_clean.csv', low_memory=False)

In [22]:
df = data.loc[data['NUMBER OF PEDESTRIANS INJURED'] > 0, ['BOROUGH', 'ON STREET NAME', 'CONTRIBUTING FACTOR VEHICLE 1']]
te = TransactionEncoder()
te_ary = te.fit(df.values).transform(df.values)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

,1 AVENUE,1 AVENUE,1 STREET,10 AVENUE,10 AVENUE,10 STREET,100 STREET,101 AVENUE,101 STREET,102 AVENUE,...,WYTHE AVENUE,WYTHE PLACE,Windshield Inadequate,YATES AVENUE,YELLOWSTONE BOULEVARD,YORK AVENUE,YORK AVENUE,YORK STREET,ZEISER PLACE,ZEREGA AVENUE
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33540,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33541,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33542,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33543,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
33544,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [20]:
frequent_itemsets = apriori(df, min_support=0.05, use_colnames=True)
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1.0)
rules.sort_values(['lift'], ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
6,(Failure to Yield Right-of-Way),(QUEENS),0.344999,0.254405,0.097481,0.282554,1.110649,0.009712,1.039236
7,(QUEENS),(Failure to Yield Right-of-Way),0.254405,0.344999,0.097481,0.383173,1.110649,0.009712,1.061888
4,(Driver Inattention/Distraction),(QUEENS),0.327053,0.254405,0.091251,0.279008,1.096711,0.008047,1.034125
5,(QUEENS),(Driver Inattention/Distraction),0.254405,0.327053,0.091251,0.358683,1.096711,0.008047,1.049320
0,(Failure to Yield Right-of-Way),(BROOKLYN),0.344999,0.312535,0.114145,0.330856,1.058620,0.006321,1.027380
1,(BROOKLYN),(Failure to Yield Right-of-Way),0.312535,0.344999,0.114145,0.365223,1.058620,0.006321,1.031860
3,(Driver Inattention/Distraction),(MANHATTAN),0.327053,0.260903,0.087971,0.268982,1.030964,0.002642,1.011051
2,(MANHATTAN),(Driver Inattention/Distraction),0.260903,0.327053,0.087971,0.337180,1.030964,0.002642,1.015278